### ISSUE TITLE
Add Rap items with Value

### ISSUE THREAD

**Issue by vikktrey123** [JartanFTW/Trade-Notifier#33]
currently, the value only shows the valued items, make an option where it adds the rap items aswell. so Value + RAP

**Comment by vikktrey123** [comment]
![image](https://user-images.githubusercontent.com/38822464/105618093-21089980-5da9-11eb-86ac-4515500c3b0b.png)
![image](https://user-images.githubusercontent.com/38822464/105618097-2665e400-5da9-11eb-90f7-393e721c1d54.png)
comparison between olympic and horizon

**Comment by JartanFTW** [comment]
Does this only add the rap of the unvalued items, or the rap of all?

**Comment by vikktrey123** [comment]
> Does this only add the rap of the unvalued items, or the rap of all?

rolimons shows different values for different rap items so idk
