### ISSUE TITLE
Hardcode Minimum Rolimons Time Interval

### ISSUE THREAD

**Issue by JartanFTW** [JartanFTW/Trade-Notifier#36]
As title says, hardcode in a minimum rolimons value grab time interval of 60 seconds as per request from Rolimon.

**Comment by nwho99** [comment]
Wouldn't it just be better to only grab values when a trade has been completed?
This would make sure that you **always, no matter what** have the correct values & it would put less stress on the Values API since trades only get accepted about every 6-12 hours.
