### ISSUE TITLE
Add outbound notifier

### ISSUE THREAD

**Issue by Fungus254** [JartanFTW/Trade-Notifier#59]
just like completed trade notifier but for outbounds

**Comment by HardWare68** [comment]
Personally, I oppose this just because since trade bots go so fast, it’d get very spammy.

**Comment by Fungus254** [comment]
> Personally, I oppose this just because since trade bots go so fast, it’d get very spammy.

**Comment by JartanFTW** [comment]
There was no real reason to close this. Just because one person doesn't like a **toggleable** feature, doesn't mean it shouldn't be implemented.
Thanks to the way Horizon is programmed, I can implement this in about 5 extra lines, and 3 other line slight alterations. This will be implemented.
