### ISSUE TITLE
crash error

### ISSUE THREAD

**Issue by vikktrey123** [JartanFTW/Trade-Notifier#61]
[02 06 2021 08 25 42.log](https://github.com/JartanFTW/Trade-Notifier/files/5939399/02.06.2021.08.25.42.log)

**Comment by JartanFTW** [comment]
Horizon currently excepts httpx.ConnectTimeout error in this instance, but this error threw a httpcore.ConnectTimeout error, which isn't handled. Add handling for httpcore.ConnectTimeout error that acts identical to httpx.ConnectTimeout handler.

**Comment by JartanFTW** [comment]
Misread the log file. This is a different error that needs handling added for it:
httpx.ConnectError: [Errno 11001] getaddrinfo failed

Along with this, handling needs to be added for httpx.ReadTimeout same as httpx.ConnectTimeout
