### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by Garrett0429** [JartanFTW/Trade-Notifier#77]
Add feature to notifier, so it will restart every 2 hours to ensure stability of the software.

**Comment by JartanFTW** [comment]
This shouldn't be necessary. Horizon is stable.

**Comment by Garrett0429** [comment]
I request this feature because horizon closed by itself after few days of constantly running

**Comment by JartanFTW** [comment]
Please be my guest in providing your log file so the issue can actually be solved rather than an auto-restart being thrown on it to hide the issue.

**Comment by Garrett0429** [comment]
Will send log next time when this incident happen because I stopped using notifier and trade bot for awhile because of UUC incident.

**Comment by JartanFTW** [comment]
Alright. What version were you on when the issue last occurred?

**Comment by JartanFTW** [comment]
Closing due to irrelevancy. If you encounter the issue again, open a new Issue providing the log file.
